$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part1.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part2.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part3.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part4.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part5.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part6.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part7.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part8.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part9.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part10.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part11.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part12.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part13.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part14.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part15.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part16.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part17.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part18.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part19.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part20.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part21.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part22.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part23.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part24.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part25.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part26.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part27.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part28.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part29.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part30.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part31.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part32.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part33.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part34.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part35.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part36.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part37.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part38.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part39.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part40.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part41.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part42.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part43.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part44.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part45.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part46.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part47.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part48.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part49.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part50.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part51.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part52.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part53.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part54.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part55.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part56.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part57.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part58.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part59.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part60.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part61.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part62.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part63.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part64.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part65.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part66.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part67.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part68.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part69.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part70.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part71.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part72.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part73.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part74.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part75.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part76.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part77.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part78.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part79.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part80.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part81.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part82.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part83.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part84.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part85.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part86.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part87.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part88.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part89.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part90.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part91.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part92.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part93.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part94.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part95.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part96.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part97.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part98.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part99.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part100.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"
$CSVimport = Import-Csv "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\Dpac\Tenants\tenants22dec-part101.csv"
& "C:\Users\Tom klein Koerkamp\OneDrive - Your Hosting B.V\WindowsPowerShell\actieve subs.ps1"